#spring.application.name=ms1
#spring.profiles.active=default
#spring.cloud.config.uri=http://localhost:8888/
#server.port=8081


spring:
  application:
    name: ms1
  profiles:
    active:
    - default
  cloud:
    config:
      uri:
      - http://localhost:8888/
  security:
    user:
      name: testnogit
server:
  port: 0
eureka:
  client:
    serviceUrl:
      defaultZone: ${EUREKA_URI:http://localhost:8761/eureka}
  instance:
    preferIpAddress: true